{
 "title": "Example",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Queue Lengths",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "example_queue", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Request Heatmap (%)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (sum(example_request_duration_seconds_bucket{}) by (le) / ignoring (le) group_left sum(example_request_duration_seconds_count{}))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Total Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(example_requests[5m]))",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "Request Rate by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(example_requests[5m])) by (status_code)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Request Rate by Pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(example_requests[5m])) by (pod)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "[counters] sum(example_requests) by (status_code)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(example_requests) by (status_code)"
    }
   ]
  }
 ]
}